baitap_mvc_3/Areas/Admin/Controllers/AdminProductController.cs
using baitap_mvc_3.App_Start;
using baitap_mvc_3.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace baitap_mvc_3.Areas.Admin.Controllers
{
    public class AdminProductController : Controller
    {
        //Menu
        [AdminAuthenrize(idChucnang = 1)]
        public ActionResult ProductMenu()
        {
            baitap_mvc2Entities db = new baitap_mvc2Entities();
            List<Product> productList = db.Products.ToList();
            return View(productList);
        }
        //Upload Image
        void UploadImage(Product model, List<HttpPostedFileBase> fileImages)
        {
            var path = "";
            foreach (var item in fileImages)
            {
                if (item != null)
                {
                    if (Path.GetExtension(item.FileName).ToLower() == ".jpg" || Path.GetExtension(item.FileName).ToLower() == ".png")
                    {
                        //save image in Data folder
                        path = Path.Combine(Server.MapPath("/Data/")) + item.FileName;
                        item.SaveAs(path);
                        //save image from Data in model
                        Image img = new Image();
                        img.Url = "/Data/" + item.FileName;
                        img.ProductID = model.ID;
                        model.Images.Add(img);
                    }
                }
            }
        }
        //Create
        [AdminAuthenrize(idChucnang = 2)]
        public ActionResult ProductCreate()
        {
            baitap_mvc2Entities db = new baitap_mvc2Entities();
            ViewBag.sizeList = db.Sizes.ToList();
            return View();
        }
        [HttpPost]
        public ActionResult ProductCreate(Product model, int[] selectedSize, List<HttpPostedFileBase> fileImages)
        {
            baitap_mvc2Entities db = new baitap_mvc2Entities();
            //add attributes
            model.Quantity = 1;
            if(selectedSize != null)
            {
                model.Sizes = db.Sizes.Where(m => selectedSize.Contains(m.ID)).ToList();
            }
            db.Products.Add(model);
            //add image
            UploadImage(model, fileImages);

            db.SaveChanges();
            return RedirectToAction("ProductMenu");
        }
        //Edit
        [AdminAuthenrize(idChucnang = 3)]
        public ActionResult ProductEdit(int? id)
        {
            if(id == null)
            {
                return View("ProductMenu");
            }
            baitap_mvc2Entities db = new baitap_mvc2Entities();
            Product model = db.Products.Find(id);
            ViewBag.sizeList = db.Sizes.ToList();
            return View(model);
        }
        [HttpPost]
        public ActionResult ProductEdit(Product model, int[] selectedSize, List<HttpPostedFileBase> fileImages)
        {
            baitap_mvc2Entities db = new baitap_mvc2Entities();
            var productUpdate = db.Products.Find(model.ID);

            //gán productUpdate = giá trị từ Form
            productUpdate.Name = model.Name.Trim();
            productUpdate.Price = model.Price;
            productUpdate.Color = model.Color.Trim();
            productUpdate.Decription = model.Decription.Trim();
            productUpdate.BrandID = model.BrandID;
            productUpdate.CategoryID = model.CategoryID;
            //xóa các quan hệ N-N của model cũ với bảng Size
            productUpdate.Sizes.Clear();
            if (selectedSize != null)
            {
                productUpdate.Sizes = db.Sizes.Where(m => selectedSize.Contains(m.ID)).ToList();
            }
            //img
            UploadImage(productUpdate, fileImages);

            db.SaveChanges();
            return RedirectToAction("ProductMenu");
        }
        public JsonResult ImageDelete(int imageID)
        {
            baitap_mvc2Entities db = new baitap_mvc2Entities(); 
            var image = db.Images.Find(imageID);
            db.Images.Remove(image);
            db.SaveChanges();
            return Json(new {status = "success"});
        }
        public JsonResult ImageAdd(int imageID)
        {
            baitap_mvc2Entities db = new baitap_mvc2Entities();
            var image = db.Images.Find(imageID);
            db.Images.Remove(image);
            db.SaveChanges();
            return Json(new { status = "success" });
        }
        //Delete
        [AdminAuthenrize(idChucnang = 4)]
        public ActionResult ProductDelete(int id)
        {
            baitap_mvc2Entities db = new baitap_mvc2Entities();
            Product productDel = db.Products.Find(id);
            db.Products.Remove(productDel);
            db.SaveChanges();
            return RedirectToAction("ProductMenu");
        }
    }
}

baitap_mvc_3/Areas/Admin/Views/AdminProduct/ProductCreate.cshtml
@model baitap_mvc_3.Models.Product

@{
    ViewBag.Title = "ProductCreate";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Product Create</h2>

@using (Html.BeginForm("ProductCreate", "AdminProduct", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Product</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Decription, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Decription, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Decription, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BrandID, "Brand", htmlAttributes: new { @class = "control-label col-md-2" })
        @{
            var brandList = new baitap_mvc_3.Models.baitap_mvc2Entities().Brands.ToList();
            IEnumerable<SelectListItem> brandSelectList = brandList.Select(x => new SelectListItem { Value = x.ID.ToString(), Text = x.Name });
        }
        <div class="col-md-10">
            @Html.DropDownList("BrandID", brandSelectList, "--Select Brand--", htmlAttributes: new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CategoryID, "Category", htmlAttributes: new { @class = "control-label col-md-2" })
        @{
            var categoryList = new baitap_mvc_3.Models.baitap_mvc2Entities().Categories.ToList();
            IEnumerable<SelectListItem> cateSelectList = categoryList.Select(x => new SelectListItem { Value = x.ID.ToString(), Text = x.Name });
        }
        <div class="col-md-10">
            @Html.DropDownList("CategoryID", cateSelectList, "--Select Category--", htmlAttributes: new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Sizes, "Size", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @foreach (var item in ViewBag.sizeList)
            {
                <input class="form-check-input" id="selectedSize" name="selectedSize" type="checkbox" value="@item.ID" /> @item.Size1
            }
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Images, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input multiple type="file" name="fileImages" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "ProductMenu")
</div>

baitap_mvc_3/Areas/Admin/Views/AdminProduct/ProductEdit.cshtml
@model baitap_mvc_3.Models.Product

@{
    ViewBag.Title = "ProductEdit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>ProductEdit</h2>

@using (Html.BeginForm("ProductEdit", "AdminProduct", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Decription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Decription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Decription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @{
                var brandList = new baitap_mvc_3.Models.baitap_mvc2Entities().Brands.ToList();
                IEnumerable<SelectListItem> brandSelectList = brandList.Select(item => new SelectListItem { Value = item.ID.ToString(), Text = item.Name });
            }
            @Html.LabelFor(model => model.BrandID, "BrandID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BrandID", brandSelectList, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @{
                var categoryList = new baitap_mvc_3.Models.baitap_mvc2Entities().Categories.ToList();
                IEnumerable<SelectListItem> categorySelectList = categoryList.Select(item => new SelectListItem { Value = item.ID.ToString(), Text = item.Name });
            }
            @Html.LabelFor(model => model.CategoryID, "CategoryID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryID", categorySelectList, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sizes, "Size", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @foreach (var item in ViewBag.sizeList)
                {
                    if (Model.Sizes.Contains(item))
                    {
                        <input class="form-check-input" id="selectedSize" name="selectedSize" type="checkbox" value="@item.ID" checked /> @item.Size1
                    }
                    else
                    {
                        <input class="form-check-input" id="selectedSize" name="selectedSize" type="checkbox" value="@item.ID" /> @item.Size1
                    }
                }
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Images, htmlAttributes: new { @class = "control-label col-md-2" })
            @if (Model.Images.Count() > 0)
            {
                foreach (var image in Model.Images)
                {
                    <div class="col-md-2">
                        <input type="image" name="fileImages" id="image-@image.ID" value="" src="@image.Url" alt="Not found" style="height: 100px; width: 100px" />
                        <a class="btn btn-danger" id="btn-delete-@image.ID" onclick="DeleteImage(@image.ID)">x</a>
                    </div>
                }
            }
            else
            {
                <div class="col-md-10">
                    <img class="img-fluid w-100" src="~/Data/OIP.jpg" alt="Not found" style="height: 100px; width: 100px">
                </div>
            }
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Add image</label>
            <div class="col-md-10">
                <input class="form-group" multiple type="file" name="fileImages" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ProductMenu")
</div>

@section ProEdit{
    <script>
        function DeleteImage(imageID) {
            var productID = @Model.ID;
            $.ajax({
                url: '/Admin/AdminProduct/ImageDelete',
                type: 'post',
                data: { imageID: imageID },
                success: function (data) {
                    $("#image-" + imageID).remove();
                    $("#btn-delete-" + imageID).remove();
                }
            })
        }
    </script>
}

baitap_mvc_3/Areas/Admin/Views/AdminProduct/ProductMenu.cshtml
@model IEnumerable<baitap_mvc_3.Models.Product>

@{
    ViewBag.Title = "ProductMenu";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>ProductMenu</h2>

<p>
    @Html.ActionLink("Create New", "ProductCreate", null, htmlAttributes: new { @class = "btn btn-primary" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Images)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Color)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sizes)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Decription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Brand)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @{
                    if (item.Images.Count(m => m.ProductID == item.ID) > 0)
                    {
                        <img class="slide" src="@item.Images.ToList()[0].Url" alt="Not found" style="height: 100px; width: 100px">
                        if (item.Images.Count(m => m.ProductID == item.ID) > 1)
                        {
                            <div id="slide-@item.ID" style="display: none">
                                @for (int i = 1; i < item.Images.Count; i++)
                                {
                                    <img class="slide" src="@item.Images.ToList()[i].Url" alt="Not found" style="height: 100px; width: 100px">
                                }
                            </div>
                            <a class="btn btn-primary" id="btn-expand-@item.ID" onclick="ExpandImage(@item.ID)">+</a>
                            <a class="btn btn-primary" id="btn-hide-@item.ID" onclick="HideImage(@item.ID)" style="display: none">-</a>
                        }
                    }
                    else
                    {
                        <img class="img-fluid w-100" src="~/Data/OIP.jpg" alt="Not found" style="height: 100px; width: 100px">
                    }
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Color)
            </td>
            <td>
                @if (item.Sizes.Count > 0)
                {
                    <div class="d-flex flex-row" style="display: flex">
                        @foreach (var size in item.Sizes)
                        {
                            <div class="p-2">@size.Size1&ensp;</div>
                        }
                    </div>
                }
                else
                {
                    <p>Out of size</p>
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Decription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Brand.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "ProductEdit", new { id = item.ID }, htmlAttributes: new { @class = "btn btn-primary" })
                @Html.ActionLink("Delete", "ProductDelete", new { id = item.ID }, htmlAttributes: new { @class = "btn btn-danger" })
            </td>
        </tr>
    }

</table>
@Html.ActionLink("Back To Menu", "Index", "AdminHome")

@section productMenu{
    <script>
        function ExpandImage(productID) {
            var slide = $("#slide-" + productID);
            slide.css({ "display": "block" });
            $("#btn-hide-" + productID).show();
            $("#btn-expand-" + productID).css({ "display": "none" });
        }
        function HideImage(productID) {
            var slide = $("#slide-" + productID);
            slide.css({ "display": "none" });
            $("#btn-expand-" + productID).show();
            $("#btn-hide-" + productID).css({ "display": "none" });
        }
    </script>
}